### ISSUE TITLE
Release datos 0.3.0

### ISSUE THREAD

**Issue by maurolepore** [cienciadedatos/datos#119] opened 2020-04-19 13:01 UTC
Relates to #108 

Prepare for release: 
 
* [x] Check that description is informative 
* [x] Check licensing of included files 
* [x] `devtools::build_readme()` 
* [x] `usethis::use_cran_comments()` 
* [x] `devtools::check(remote = TRUE, manual = TRUE)` 
* [x] `devtools::check_win_devel()` 
    2020-06-02: https://win-builder.r-project.org/E9ZbuyrYmLPR/00check.log

```
Status: 1 NOTE
* New submission
* Package was archived on CRAN
```

* [x] `rhub::check_for_cran()`:

2020-06-02, branch remote-checks:  

   https://builder.r-hub.io/status/datos_0.2.0.9000.tar.gz-8592b3e7079d455ca960414aeee26cb2
   https://builder.r-hub.io/status/datos_0.2.0.9000.tar.gz-bc4490152da84b8eb26f11c94e3501ad
   https://builder.r-hub.io/status/datos_0.2.0.9000.tar.gz-acbc755df10e41c1b301bf57744d5723

I see a problem on rhub with r-devel running on windows that I don't see with  `devtools::check_win_devel()`. The problem may relate to rhub only. `translate()` errors on rhub with Windows and R-devel. The error refers to vctrs and is likely caused vctrs 0.3.0 is required by some package we depend on  (likely dplyr) but vctrs 0.3.0 may not be on rhub right now. But we had no problem with `devtools::check_win_devel()` -- which is what CRAN will test. I would submit anyway.

```
> rhub::check(platform = "windows-x86_64-devel")


Build ID:	datos_0.2.0.9000.tar.gz-55eebba3fe624d43b20add2f431cd3d7
Platform:	Windows Server 2008 R2 SP1, R-devel, 32/64 bit
Submitted:	4 minutes 11.1 seconds ago
Build time:	4 minutes 9 seconds
ERRORS:
* checking for missing documentation entries ... ERROR
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'vctrs' 0.2.4 is already loaded, but >= 0.3.0 is required
Calls: <Anonymous> ... unlist -> lapply -> FUN -> eval -> eval -> translate
Execution halted
* checking tests ...
  Running 'testthat.R'
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
   10. base::loadNamespace(name)
   12. base::loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  == testthat results  ===========================================================
  1. Error: Load from spec works for:tabla1 (@test-translations.R#25) 
  
  2. Error: Load from spec works for:tabla2 (@test-translations.R#25) 
  [ OK: 125 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 7 ]
  3. Error: Load from spec works for:tabla3 (@test-translations.R#25) 
  4. Error: Load from spec works for:tabla4a (@test-translations.R#25) 
  5. Error: Load from spec works for:tabla4b (@test-translations.R#25) 
  6. Error: Load from spec works for:tabla5 (@test-translations.R#25) 
  7. Error: Load from spec works for:oms (@test-translations.R#25) 
  
  Error: testthat unit tests failed
  Execution halted
```

* [x] Update `cran-comments.md` 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('minor')` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()` 
* [x] Update install instructions in README

**Comment by rivaquiroga** [comment] 2020-04-19 16:40
Shouldn't it be `0.3`? Is more than[ just a patch](https://r-pkgs.org/release.html). Not having to install the packages with the datasets you want to translate looks more like a minor release. Is like a new feature. That, plus the changes made in https://github.com/cienciadedatos/datos/pull/112 afected the book translation.

**Comment by maurolepore** [comment] 2020-04-19 18:33
Thanks @rivaquiroga, I agree. See #121. You may want to edit NEWS.md.

**Comment by rivaquiroga** [comment] 2020-06-14 12:37
@pachamaltese, @maurolepore we have a problem with the checks for Windows. It seems that the package can't be installed in that platform.
The notes are related to the change in the maintainer. So nothing to worry about.

```
package datos_0.3.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/datos_0.3.0_20200614_002636/Windows/00check.log>
Status: 1 ERROR, 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/datos_0.3.0_20200614_002636/Debian/00check.log>
Status: 1 NOTE
```

**Comment by rivaquiroga** [comment] 2020-06-14 12:41
The problem is with `vctrs`. The same we got on rhub

**Comment by maurolepore** [comment] 2020-06-14 13:01
The problem maybe temporary:

![image](https://user-images.githubusercontent.com/5856545/84594058-3aaa3180-ae15-11ea-886a-a19647d4107b.png)

--

I would retry now. My checks on Windows now pass:

1. on rhub: https://builder.r-hub.io/status/datos_0.3.0.tar.gz-e6e92c640c984bd0b0b0a03862bc6429
2. on win-builder: https://win-builder.r-project.org/3C69Rq5yq390/00check.log

Also, in trying things out I did a hack that might be a bad idea. I cloned the source of pillar and vctrs, checked out the commit for the latest release on CRAN (not the head of the development version) and uploaded that to winbuilder (for R devel). Then uploaded datos again. This is to check datos in the context of the released version of pillar and vctrs. But then I reviewed https://win-builder.r-project.org/ and I realize I should have first asked for permission to the maintainers of pillar and vctrs. 

> Please do not upload packages of other maintainers (particularly not without changing the Maintainer field to your own e-mail address, if you have permissions to do that).

I'm sorry @krlmlr and @lionel-. What can I do to revert things back so you experience no trouble? Should I checkout the head of your repos and upload to winbuilder? Do someting else? Do nothing?

**Comment by rivaquiroga** [comment] 2020-06-14 13:34
😱 I didn't know it was possible for that to happen

**Comment by krlmlr** [comment] 2020-06-14 14:57
Thanks for the heads-up. I think you did right, no need to worry. It's new to me that winbuilder installs dev versions of packages into its library.

**Comment by rivaquiroga** [comment] 2020-06-14 16:32
```
package datos_0.3.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/datos_0.3.0_20200614_164009/Windows/00check.log>
Status: 1 ERROR, 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/datos_0.3.0_20200614_164009/Debian/00check.log>
Status: NA (check log incomplete, web timeout?)


More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/datos_0.3.0_20200614_164009/>
```

**Comment by rivaquiroga** [comment] 2020-06-14 16:57
:nerd_face: 
```
package datos_0.3.0.tar.gz has been auto-processed and is pending a manual inspection of this new CRAN submission. A CRAN team member will typically respond to you within the next 10 working days. For technical reasons you may receive a second copy of this message when a team member triggers a new check.

Log dir: <https://win-builder.r-project.org/incoming_pretest/datos_0.3.0_20200614_180600/>
The files will be removed after roughly 7 days.
Installation time in seconds: 23
Check time in seconds: 145 
R Under development (unstable) (2020-06-12 r78687)

Pretests results:
Windows: <https://win-builder.r-project.org/incoming_pretest/datos_0.3.0_20200614_180600/Windows/00check.log>
Status: 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/datos_0.3.0_20200614_180600/Debian/00check.log>
Status: 1 NOTE
```

**Comment by maurolepore** [comment] 2020-06-14 17:03
Yay! Fingers crossed here :)

**Comment by pachadotdev** [comment] 2020-06-14 17:36
sorry for the very late reply, I'm in a ascetic state
it shouldn't be so problematic that the Windows build runs with notes, as it is to create a binary
I have a Windows laptop here if you need to test anything besides gh-actions

**Comment by rivaquiroga** [comment] 2020-06-16 01:06
`datos` is back on CRAN, so I'm closing this issue :rocket:
Thanks @maurolepore, @pachamaltese and @jonkeane

**Closed as completed by rivaquiroga** 2020-06-16 01:06 UTC
